# -*- coding: utf-8 -*-
"""Cópia de Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGA3TYcV_IsReHcPttXmUjlkq9WOWe7k

1. Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

numero_1 = int(input("digite um numero "))
numero_2 = int(input("digite outro numero "))

SOMA = numero_1 + numero_2

if SOMA >= 15:
  print("maior ou igual a 15")
else:
  print("menor que 15")

"""2. Faça um programa que recebendo um valor inteiro, informe se o número é positivo,
negativo ou neutro.

"""

numero_1 = int(input("digite um numero "))

if numero_1 == 0:
 print("numero neutro")
elif numero_1 <0:
 print("numero negativo")
else:
 print("numero positivo")

"""3. Leia a idade e informe se a pessoa é maior ou menor de idade

"""

nome_1 = str(input("qual seu nome ? "))
idade_1 = int(input("qual sua idade ? "))

if idade_1 >=18:
 print("voce e maior de idade")
else:
  print("voce e menor de idade")

"""4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.
"""

usuario_1 = int(input("qual a temperatura atual? "))

if usuario_1 <21:
 print("esta frio")
 print("pega a blusa em!")

elif usuario_1 >25 and 35:
  print("esta calor")
else:
   print("esta um clima agradavel")

"""5. Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes.
"""

numero_1 = int(input("digite um numero "))
numero_2 = int(input("digite o segundo numero "))

if numero_1 == numero_2:
  print("numeros iguais")
else:
  print("numeros diferentes")

"""6. Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:
 ACESSO PERMITIDO caso a senha seja válida.
 ACESSO NEGADO caso a senha seja inválida.
"""

usuario_1 = int(input("digite a senha de 4 digitos? "))

senha = 1234

if usuario_1 == senha:
  print("acesso permitido")
else:
  print("acesso negado")

"""7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado.

"""

nota_1 = int(input("digite sua primeira nota ? "))
nota_2 = int(input("digite sua segunda nota ? "))

media = (nota_1 + nota_2)/2

if media >=5<7:
 print("voce precisa fazer o exame!!!")
elif media >=7:
 print("aprovado")
else:
  print("reprovado")

"""8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os
gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
primeiro time ou do segundo time.
"""

time_1 = str(input("qual seu time ? "))
time_2 = str(input("qual seu rival? "))

resultado_1 = int(input("qual o resultado do seu time ? "))
resultado_2 = int(input("qual o resultado do seu rival ? "))

if resultado_1 > resultado_2:
  print(f"o {time_1}  ganhou!!!!")
  print("ganhamos porraaaaa")

elif resultado_1 < resultado_2:
  print(f"o {time_2} ganhou!!!")
  print("perdeu pro rival fioti")
else:
  print("empatou o jogo")

"""9. Faça um Programa que pergunte em que turno você estuda. Peça para digitar Mmatutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
"""

usuario_1 = str(input("qual o turno que voce estuda ? "))

if usuario_1 == "manha" :
  print("Bom Dia!")
elif usuario_1 == "tarde":
  print("Boa Tarde!")
else:
  print("Boa Noite!")

"""10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a
classificação etária de acordo com as faixas de valores:
 Criança para 0 até 11 anos;
 Adolescente para 12 até 18 anos;
 Jovem para 19 até 24 anos;
 Adulto para 25 até 40 anos;
 Meia Idade para 41 até 60 anos;
 Idoso acima de 60 anos.

"""

nome_1 = str(input("qual seu nome? "))
idade_1 = int(input("qual sua idade? "))