# -*- coding: utf-8 -*-
"""IF E ELSE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WRcAt6SofuQD4KwRtg6SrFiu70UC9zYk
"""

#Python

nota_1 = 5
nota_2 = 9

xresult = (nota_1 + nota_2) /2
print (xresult)

if (xresult)>=7:
  print ("aprovado")

else:
  print ("reprovado")

"""1-Leia dois números, faça a soma e apresente caso seja maior que 15."""

numero_1 = float(input('escreva um numero '))
numero_2 = float(input('escreva outro numero '))

soma = numero_1 + numero_2

if soma >= 15:
  print('acertou')

else:
  print('errou')

"""2- Faça um programa que recebendo um valor inteiro, informe se o número é positivo,
negativo ou neutro.
"""

valor_1 = int(input('digite um numero '))

if valor_1 >0:
  print("positivo")

elif valor_1 <0:
  print("negativo")

else:
  print("neutro")

"""3_leia a idade e informe se a pessoa é maior ou menor de idade"""

idade = float(input("digite sua idade" ))

if idade >= 18:
  print("maior de idade")

else:
  print("menor de idade")

"""4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.
"""

xresult = int(input("qual a temperatura agora "))

if xresult <= 22:
 print("esta frio hoje")

elif xresult <=25 and xresult >=21:
 print("esta um clima agradavel hoje")

else:
 print("esta calor hoje")

"""5-Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes.
"""

numero_1 = int(input("informe um numero "))
numero_2 = int(input("informe o segundo numero "))

if  numero_1 == numero_2:
 print("são iguais")

else:
 print("são diferentes")

"""6 -Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:
 ACESSO PERMITIDO caso a senha seja válida.
 ACESSO NEGADO caso a senha seja inválida.
"""

senha_1 = int(input("digite uma senha de 4 digitos" ))

if senha_1 == 1234:
 print("acesso permitido")

else:
  print("acesso negado")

"""7-Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado.
"""

aluno_1 = int(input("digite sua nota "))